sudo: false

os:
  - linux
#   - osx

language: d

d:
  - ldc-1.4.0
  - dmd

env:
  - ARCH="x86_64"

before_install:
  - sudo apt-get install -qq python-numpy
  - cd test && python test_npy_fileio.py && cd ..

install:
  - dub fetch doveralls

script:
  - dub test --arch "$ARCH" --build=unittest-cov
  - dub run doveralls

deploy:
  d: dmd
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: docs
  on:
    branch: master
    condition: if [[ $DC = dmd ]]; then make doc; fi
