sudo: false

os:
  - linux

language: d

d:
  - ldc
  - dmd

env:
  - ARCH="x86_64"

matrix:
  include:
    - {os: linux, d: ldc, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
    - {os: linux, d: dmd, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}

before_install:
  - sudo apt-get install -qq python-numpy
  - cd test && python test_npy_fileio.py && cd ..

script:
  - dub test --arch "$ARCH" --build=unittest-cov
  # https://github.com/vibe-d/vibe.d/blob/master/README.md#additional-setup-on-linux-debianubuntumint
  - if [ $DC = dmd ] && [ $ARCH = "x86_64" ]; then sudo apt-get install -qq libevent-dev libssl-dev; fi
  - if [ $DC = dmd ] && [ $ARCH = "x86_64" ]; then make doc; fi
  # https://github.com/blog/572-bypassing-jekyll-on-github-pages
  - if [ $DC = dmd ] && [ $ARCH = "x86_64" ]; then touch docs/.nojekyll; fi

after_success:
 - bash <(curl -s https://codecov.io/bash)

deploy:
  d: dmd
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: docs
  on:
    branch: master
    condition: $DC = dmd && $ARCH = "x86_64"
