sudo: false

os:
  - linux
#   - osx

language: d

d:
  - ldc-1.2.0
  - dmd

env:
  - ARCH="x86_64"

install:
  - dub fetch doveralls

script:
  - dub test --arch "$ARCH" --build=unittest-cov
  - dub run doveralls
